LAYERS = [
        {"Teste Sistema Elétrico Planejado": "0"},
        # {"EOL - Expansão Planejada": "1"},
        # {"UFV - Expansão Planejada": "2"},
        # {"UHE - Expansão Planejada": "3"},
        # {"PCH - Expansão Planejada": "4"},
        # {"CGH - Expansão Planejada": "5"},
        # {"UTE Biomassa - Expansão Planejada": "6"},
        # {"UTE Fóssil - Expansão Planejada": "7"},
        # {"UTE Nuclear - Expansão Planejada": "8"},
        {"Teste Subestações - Expansão Planejada": "9"},
        # {"Linhas de Transmissão - Expansão Planejada": "10"},
        # {"Subsistema do Sistema Interligado Nacional": "11"},
        # {"Unidades da Federação": "12"},
        # {"Sistema Elétrico Existente": "13"},
        # {"EOL - Base Existente": "14"},
        # {"UFV - Base Existente": "15"},
        # {"UHE - Base Existente": "16"},
        # {"PCH - Base Existente": "17"},
        # {"CGH - Base Existente": "18"},
        # {"UTE Biomassa - Base Existente": "19"},
        # {"UTE Fóssil - Base Existente": "20"},
        # {"UTE Nuclear - Base Existente": "21"},
        # {"Subestações - Base Existente": "22"},
        # {"Linhas de Transmissão - Base Existente": "23"},
        # {"Subsistema do Sistema Interligado Nacional": "24"},
        # {"Unidades da Federação": "25"},
        # {"Biocombustíveis": "26"},
        # {"Plantas de etanol": "27"},
        # {"Plantas de biodiesel": "28"},
        # {"Plantas de biogás": "29"},
        # {"Infraestrutura de Combustíveis Líquidos": "30"},
        # {"Bases de Combustíveis": "31"},
        # {"Bases de GLP": "32"},
        # {"Instalações de Processamento": "33"},
        # {"Terminais de Petróleo e Derivados": "34"},
        # {"Infraestrutura de Gás Natural": "35"},
        # {"Terminais de GNL": "36"},
        # {"Polos de processamento de gás natural": "37"},
        # {"Estações de compressão": "38"},
        # {"Pontos de entrega de gás natural": "39"},
        # {"Dutos de escoamento": "40"},
        # {"Gasodutos de transporte": "41"},
        # {"Gasodutos de distribuição": "42"},
        # {"Exploração e Produção de Petróleo e Gás": "43"},
        # {"Unidades Produtivas": "44"},
        # {"Áreas sob Contrato": "45"},
        # {"Áreas da União": "46"},
        # {"Histórico de Ofertas": "47"},
        # {"Histórico de Blocos Ofertados (Modalidade, Rodada": "48"},
        # {"Oferta Permanente": "49"},
        # {"Resumo ZNMT": "50"},
        # {"Bacia Efetiva Geográfica": "51"},
        # {"Bacia Efetiva Probabilística": "52"},
        # {"Tipo de Fluido Predominante": "53"},
        # {"Recursos Não Convencionais": "54"},
        # {"Importância Petrolífera de Área - IPA": "55"},
        # {"IPA Total": "56"},
        # {"IPA Intensidade Exploratória": "57"},
        # {"IPA Atividade Exploratória": "58"},
        # {"IPA Prospectividade": "59"},
        # {"IPA Evidência Direta de Hidrocarbonetos": "60"},
        # {"IPA Necessidade de Conhecimento": "61"},
        # {"IPA Infraestrutura de Abastecimento": "62"},
        # {"Dados Culturais": "63"},
        # {"Polígono do Pré Sal Legal": "64"},
        # {"Ambiente de E&P": "65"},
        # {"Bacias Sedimentares": "66"},
        # {"Embasamento": "67"},
        # {"Meio Ambiente": "68"},
        # {"Caverna (Cecav)": "69"},
        # {"Terra Indígena Estudo (Funai)": "70"},
        # {"Sítio Arqueológico (Iphan)": "71"},
        # {"Terra Indígena (Funai)": "72"},
        # {"Terra Quilombola (Incra)": "73"},
        # {"Projeto de Assentamento (Incra)": "74"},
        # {"Unidade de Conservação (MMA)": "75"},
        # {"Mapoteca UCs Eletrobras 2019": "76"},
        # {"Estudos da EPE e Recursos Energéticos": "77"},
        # {"Estudos da EPE": "78"},
        # {"Estudos de Viabilidade Hidrelétrica": "79"},
        # {"Estudos de Inventário Hidrelétrico e AAI": "80"},
        # {"Estudo Ambiental da Área Sedimentar do Solimões": "81"},
        # {"Recursos": "82"},
        # {"Torres Anemométricas do AMA": "83"},
        # {"Eólico (Global Atlas)": "84"},
        # {"Velocidade do vento a 100 metros (m/s)": "85"},
        # {"Velocidade do vento a 150 metros (m/s)": "86"},
        # {"Velocidade do vento a 200 metros (m/s)": "87"},
        # {"Solar (INPE)": "88"},
        # {"Total diário da Irradiação Global Horizontal - média anual (Wh/m².dia)": "89"},
        # {"Total diário da Irradiação Direta Normal - média anual (Wh/m².dia)": "90"},
        # {"Total diário da Irradiação no Plano Inclinado na Latitude - média anual (Wh/m².dia)": "91"}

    ]